yanisapths/daycare-portal

- pages/create/index.js
fix upload image, convert to base64
> [HYP-1] fix upload image

- components/BtnAccept.js
- components/BtnCancel.js
- components/Footer.js
- components/Header.js
- components/Header2.js
- components/SideBar.js
- pages/_app.js
- pages/create/index.js
- pages/index.js
- pages/request/index.js
- pages/review/index.js
- pages/schedule/index.js
- pages/staff/index.js
- styles/globals.css
Jira: [HYP-23](https://happyelders.atlassian.net/browse/HYP-23)
revise header and sidebar
> [HYP-23][Daycare] Revise sidebar

- components/calendar/OLCalendar.js
- next.config.js
- package-lock.json
- package.json
- pages/index.js
- pages/request/index.js
- pages/request/request_view/ListView.js
Description
Jira: [HYP-26](https://happyelders.atlassian.net/browse/HYP-26)
> [HYP-26] Call API Request endpoint

- components/FooterSocial.js
- components/Header.js
- components/SideBar.js
- components/common/HoverCard.js
- components/common/SmallInput.js
- pages/_app.js
- pages/course/course_view/ListView.js
- pages/course/course_view/SideView.js
- pages/course/index.js
- pages/create/index.js
- pages/index.js
- pages/noClinic.js
- pages/request/index.js
- pages/review/index.js
- pages/schedule/index.js
- pages/staff/index.js
- styles/globals.css
- tailwind.config.js
- theme/index.js
Jira: [HYP-44](https://happyelders.atlassian.net/browse/HYP-44)
> [HYP-44] Add create course

- components/Header.js
- components/NavBar.js
- components/SideBar.js
- package-lock.json
- package.json
- pages/appointment/index.js
- pages/course/index.js
- pages/index.js
- pages/noClinic.js
- pages/request/index.js
- pages/review/index.js
- pages/schedule/index.js
- pages/staff/index.js
- styles/globals.css
- tailwind.config.js
Jira: [HYP-56](https://happyelders.atlassian.net/browse/HYP-56)
Revise CSS 
-Header -> color,font
-Sidebar -> color,font, action: close when click outsude, add divide line in each item, 
-Add navbar
> [HYP-56] Revise Css

- components/common/HoverCard.js
- pages/course/course_view/ListView.js
- pages/course/course_view/SideView.js
- pages/course/index.js
- pages/index.js
- pages/request/request_view/ListView.js
Jira: [HYP-57](https://happyelders.atlassian.net/browse/HYP-57)
> [HYP-57] Call course response api

- components/BtnCancel.js
- components/BtnDetails.js
- components/BtnEdit.js
- components/Header.js
- components/SideBar.js
- pages/appointment/index.js
- pages/noClinic.js
- styles/globals.css
- tailwind.config.js
Description
Jira: [HYP-56](https://happyelders.atlassian.net/browse/HYP-56)
#2
Responsive + CSS
> [HYP-56]Responsive + CSS 

- pages/create/index.js
Description
Jira: [HYP-67](https://happyelders.atlassian.net/browse/HYP-67)
- responsive mobile,tablet,labtop
- Border theme
> [HYP-67] Revise create daycare page

- components/AddBtn.js
- components/BtnCancel.js
- components/BtnDetails.js
- components/BtnEdit.js
- pages/create/index.js
- pages/staff/index.js
- styles/globals.css
Jira: [HYP-69](https://happyelders.atlassian.net/browse/HYP-69)
-add article tag 
-resposive mobile tablet labtop
-resizing navbar
> [HYP-69]Revise staff page

- components/FooterSocial.js
- components/NavBar.js
- components/common/HoverCard.js
- package-lock.json
- package.json
- pages/course/course_view/ListView.js
- pages/course/course_view/SideView.js
- pages/course/index.js
- styles/globals.css
- theme/index.js
Jira: [HYP-66](https://happyelders.atlassian.net/browse/HYP-66)
- active nav bar highlight color
- responsive block
- detail of course
> [HYP-66]Revise course page

- components/calendar/OLCalendar.js
- components/common/RequestListCard.js
- next.config.js
- pages/appointment/appointment_view/ListView.js
- pages/appointment/index.js
- pages/course/course_view/ListView.js
- pages/course/course_view/SideView.js
- pages/course/index.js
- pages/create/index.js
- pages/dashboard/index.js
- pages/index.js
- pages/request/FormModal.js
- pages/request/index.js
- pages/request/request_view/TableView.js
- pages/schedule/index.js
transfer to localhost url due to usage limit
> feat(api): transfer to localhost

- components/LinkGridCard.js
- components/NavBar.js
- components/SideBar.js
- components/common/BtnAdd.js
- pages/patient/AddPatientForm.js
- pages/patient/index.js
- pages/patient/patient_view/TableView.js
- styles/globals.css
Jira: [HYP-70](https://happyelders.atlassian.net/browse/HYP-70)
Add Patient Report Table
Add create patient report form modal
> [HYP-70] Add patient report page

- components/BtnDetails.js
- components/BtnEdit.js
- components/common/BtnAdd.js
- components/common/OLIconButton.js
- pages/patient/AddPatientForm.js
- pages/patient/index.js
- pages/staff/AddStaffForm.js
- pages/staff/index.js
- pages/staff/staff_view/ListView.js
Jira: [HYP-33](https://happyelders.atlassian.net/browse/HYP-33)
Add create staff modal
Call staff api
> [HYP-33] Add create staff page

- components/OLCard/PeopleReviewCard.js
- package-lock.json
- package.json
- pages/review/index.js
Jira: [HYP-76](https://happyelders.atlassian.net/browse/HYP-76)
feat(api): call review api
add: review card
> [HYP-76] Display Reviews

- components/calendar/OLCalendar.js
- components/calendar/PickCalendar.js
- pages/appointment/AddAppointmentForm.js
- pages/appointment/TimeModal.js
- pages/appointment/appointment_view/ListView.js
- pages/appointment/index.js
- pages/create/index.js
Jira: [HYP-78](https://happyelders.atlassian.net/browse/HYP-78)
Add create appointment form modal
> [HYP-78] Create Modal to allow clinic to add appointment

- components/BtnDetails.js
- components/OLCard/AppointmentListCard.js
- components/calendar/SimpleCalendar.js
- pages/appointment/appointment_view/ListView.js
- pages/appointment/index.js
- utils/calendar.js
- utils/cn.js
Jira: [HYP-85](https://happyelders.atlassian.net/browse/HYP-85)
Add Calendar on ListView
> [HYP-85] Update schedule view on appointment

- components/OLButton/SimpleChip.js
- components/OLCard/AppointmentListCard.js
- components/OLModal/AddCourse.js
- components/OLModal/AppointmentModal.js
- pages/_app.js
- pages/appointment/appointment_view/CalendarView.js
- pages/appointment/appointment_view/ListView.js
- pages/appointment/index.js
- pages/course/course_view/listView.js
Jira: [HYP-84](https://happyelders.atlassian.net/browse/HYP-84)
feat(api): call add event request
update: appointment modal
Refactor code
> [HYP-84] Allow add event list for each appointment

- components/BtnLogin.js
- components/OLCard/AppointmentListCard.js
- components/OLIcon/RoundTextIcon.js
- components/OLModal/AppointmentModal.js
- components/OLModal/RequestModal.js
- components/common/RequestListCard.js
- pages/appointment/appointment_view/ListView.js
- pages/appointment/index.js
- pages/auth/signin.js
- pages/request/request_view/ListView.js
- pages/request/request_view/TableView.js
Jira: [HYP-90](https://happyelders.atlassian.net/browse/HYP-90)
แสดงคำขอใหม่ใทั้งหมด
> [HYP-90][Clinic] Display all new requests

- components/OLCard/AppointmentTableRow.js
- components/OLModal/AddCourse.js
- components/OLModal/DetailView.js
- components/common/HoverCard.js
- package-lock.json
- package.json
- pages/course/course_view/listView.js
- pages/course/index.js
Jira: [HYP-94](https://happyelders.atlassian.net/browse/HYP-94)
> HYP-94 Add delete course

- components/OLIcon/CircleIcon.js
- components/OLIcon/RoundTextIcon.js
- components/OLModal/RequestModal.js
- components/common/RequestListCard.js
- pages/request/AddRequestForm.js
Jira: [HYP-102](https://happyelders.atlassian.net/browse/HYP-102)
-change phone number pattern
-responsive modal
-style in modal (position, font size, font color)
> [HYP-102][BUG] Request Modal - CSS พังแสดงวันเวลาผิด - ต้องแสดง วันเวลาที่นัดหมาย ไม่ใช่ที่ขอมาข้อควรระวัง ให้ขึ้นบรรทัดใหม่

- components/BtnDetails.js
- pages/staff/index.js
- pages/staff/staff_view/ListView.js
- styles/globals.css
Jira: [HYP-100](https://happyelders.atlassian.net/browse/HYP-100)
delete icon, 
reposition item in staff card for responsive
> [HYP-100][Clinic][Bug] Staff - Card ใหญ่เกิน สำหรับจอ 150 %

- components/Header.js
- components/OLModal/PatientDetailModal.js
- components/common/BannerCard.js
- pages/index.js
Jira: [HYP-99](https://happyelders.atlassian.net/browse/HYP-99)
-fix width modal
-ที่อยู่ -> ที่อยู่ปัจจุบัน
> [HYP-99]style: restyle for resposive + change text ที่อยู่

- components/OLModal/AppointmentModal.js
- pages/auth/signin.js
Jira: [HYP-113](https://happyelders.atlassian.net/browse/HYP-113)
> [HYP-113][Clinic] ถ้า สถานะเป็น reject ไม่ต้องโชว์ข้อความ “ไม่สามารถเพิ่มนัดได้เนื่องจากจำนวนนัดครบแล้ว“

- components/AppointmentView/ListView.js
- components/OLCard/AppointmentListCard.js
- components/OLCard/AppointmentTableRow.js
- components/OLCard/EventListCard.js
- components/OLModal/AppointmentModal.js
- pages/appointment/appointment_view/CalendarView.js
Jira: [HYP-115](https://happyelders.atlassian.net/browse/HYP-115)
-list view btn เสร็จสิ้น --> เสร็จสิ้นบริการนัดครั้งนี้
-table view btn  เสร็จสิ้น -->  เสร็จสิ้นการการให้บริการ
-tooltip text in modal เสร็จสิ้น --> เสร็จสิ้นการนัดครั้งนี้ , 
ยกเลิก --> ยกเลิกการนัดครั้งนี้
-ข้อความใน table view ทำให้อยู่ตรงกลาง
> [HYP-115][Clinic] แก้ปุ่ม modal - เสร็จสิ้นนัดครั้งนี้, ตาราง - เสร็จสิ้นการให้บริการ

- components/OLCard/RequestTableRow.js
- pages/request/request_view/TableView.js
Jira: [HYP-105](https://happyelders.atlassian.net/browse/HYP-105)
-change index in all request view to start with 1
-restyle text position to center
> [HYP-105 ][Clinic]  “All new requests“ view - CSS Heading positionลำดับ เริ่มจาก 1

- components/BtnLogin.js
- pages/auth/signin.js
Jira: [HYP-117](https://happyelders.atlassian.net/browse/HYP-117)
> [HYP-117][Clinic] restyle login page

- components/OLModal/PatientDetailModal.js
- pages/patient/AddPatientForm.js
Jira: [HYP-119](https://happyelders.atlassian.net/browse/HYP-119)
> [HYP-119][Clinic] ลบ upload file + hide scroll bar

- components/AppointmentView/ListView.js
- components/OLCard/AppointmentTableRow.js
Jira: [HYP-123](https://happyelders.atlassian.net/browse/HYP-123)
fix: table head
> [HYP-123][Clinic] หัวข้อตารางนัดหมาย ไม่ตรง

- components/OLCard/PeopleReviewCard.js
- pages/review/index.js
Jira: [HYP-126](https://happyelders.atlassian.net/browse/HYP-126)
fix: card width, layout
> [HYP-126][Clinic] restyle review page

- components/AppointmentView/ListView.js
- components/OLCard/AppointmentListCard.js
- components/OLCard/AppointmentTableRow.js
- components/OLCard/EventListCard.js
- components/OLCard/EventTableRow.js
- components/OLCard/PatientCard.js
- components/OLModal/AppointmentModal.js
- pages/appointment/index.js
- pages/availability/index.js
- pages/course/index.js
- pages/dashboard/index.js
- pages/patient/AddPatientForm.js
- pages/patient/index.js
- pages/patient/patient_view/TableView.js
- pages/request/index.js
- pages/request/request_view/TableView.js
- pages/schedule/index.js
- pages/staff/index.js
Jira: [HYP-95](https://happyelders.atlassian.net/browse/HYP-95)
[HYP-97](https://happyelders.atlassian.net/browse/HYP-97)
feat(api): fetch by clinic id
> [HYP-95][HYP-97] Course Page - ลบคลินิกแล้ว คอร์สที่เคยสร้างไม่หาย (course cards), ลบคลินิกแล้ว พนง.ไม่หาย

- components/BtnLogin.js
- pages/auth/signin.js
Jira: [HYP-118](https://happyelders.atlassian.net/browse/HYP-118)
> [HYP-118][Customer] restyle login page

- pages/dashboard/index.js
- pages/staff/index.js
- pages/staff/staff_view/ListView.js
Jira: [HYP-120](https://happyelders.atlassian.net/browse/HYP-120)
-restyle staff card
-delete detail btn
> [HYP-120][Clinic] ลบดูเพิ่มเติมตำแหน่ง ควรอยู่ บรรทัดเดียวกับ ชื่อ 1024, 1440 1280เพิ่มอีเมลใน card

- components/OLModal/RequestModal.js
- components/common/RequestListCard.js
- pages/dashboard/index.js
- pages/request/request_view/ListView.js
Jira: [HYP-121](https://happyelders.atlassian.net/browse/HYP-121)
> [HYP-121][Clinic] line ld position issue in request modal

- pages/staff/index.js
Jira: [HYP-140](https://happyelders.atlassian.net/browse/HYP-140)
> [HYP-140][Clinic] staff page แสดง text ไม่มีข้อมูลพนักงงาน

- components/OLModal/AppointmentModal.js
Jira: [HYP-135](https://happyelders.atlassian.net/browse/HYP-135)
fix: typo clinic on add new event
> [HYP-135] event ไม่เเสดงที่หน้านัดหมาย

- components/OLModal/AppointmentModal.js
- pages/appointment/appointment_view/CalendarView.js
Jira: [HYP-134](https://happyelders.atlassian.net/browse/HYP-134)
fix: remove events length not found, add user props to event card
> [HYP-134][Clinic] schedule view -  cannot add event form

- pages/create/index.js
Jira: [HYP-139](https://happyelders.atlassian.net/browse/HYP-139)
add: toast for image exceed size
> [HYP-139][Clinic] picture size validation 

- pages/availability/index.js
Jira: [HYP-132](https://happyelders.atlassian.net/browse/HYP-132)
reduce padding top
> [HYP-132][Clinic] availability page - reduce padding top

- pages/request/index.js
- pages/request/request_view/ListView.js
Jira: [HYP-141](https://happyelders.atlassian.net/browse/HYP-141)
text = ไม่มีคำขอรับบริการใหม่
> [HYP-141][Clinic] request page แสดง text ไม่มีข้อมูลคำขอใหม่

- components/OLModal/AppointmentModal.js
Jira: [HYP-143](https://happyelders.atlassian.net/browse/HYP-143)
> [HYP-143][Clinic] appointment modal - ข้อควรระวังขึ้นบรรทัดใหม่

- pages/patient/patient_view/TableView.js
Jira: [HYP-136](https://happyelders.atlassian.net/browse/HYP-136)
> [HYP-136][Clinic] patient- table view แก้ตาราง ให้หัวข้ออยู่ center

- components/BtnLogin.js
- pages/auth/signin.js
Jira: [HYP-144](https://happyelders.atlassian.net/browse/HYP-144)
> [HYP-144][Clinic] แก้ปุ่มล้อคอินให้เท่ากัน

- components/OLModal/AppointmentModal.js
- components/SideBar.js
- pages/auth/signin.js
- pages/noClinic.js
- styles/globals.css
Jira: [HYP-144](https://happyelders.atlassian.net/browse/HYP-144)
> [HYP-144][Clinic] แก้ปุ่มล้อคอินให้เท่ากัน + sidebar

- components/OLForm/AddAppointmentForm.js
- components/OLModal/AddCourse.js
- components/OLModal/AppointmentModal.js
- package-lock.json
- pages/availability/index.js
- pages/patient/AddPatientForm.js
- pages/staff/AddStaffForm.js
- styles/globals.css
- theme/index.js
Jira: [HYP-145](https://happyelders.atlassian.net/browse/HYP-145)
> [HYP-145][Clinic] แก้สีฟอร์มเพิ่มนัดให้ชัดขึ้น

- components/OLModal/AppointmentModal.js
- components/OLModal/BodyChartCanvas.js
- components/OLModal/EventBodyChart.js
Jira: [HYP-147](https://happyelders.atlassian.net/browse/HYP-147)
add: penColor, fix open dialog
> [HYP-147] add pen Color and not on bodychart

- components/Header.js
- pages/create/index.js
- pages/profile/index.js
Jira: [HYP-38](https://happyelders.atlassian.net/browse/HYP-38)
> [HYP-38] Send back daycare owner's profile image Url

- components/FooterSocial.js
Jira: [HYP-150](https://happyelders.atlassian.net/browse/HYP-150)
> [HYP-150]Footer - Change contract to be email

- components/OLModal/RequestModal.js
Jira: [HYP-153](https://happyelders.atlassian.net/browse/HYP-153)
style: fix padding precaution
> [HYP-153]restyle request modal precaution + hidden address when select clinic

- components/OLForm/EditCourseForm.js
- components/OLModal/DetailView.js
- components/common/HoverCard.js
- pages/course/course_view/listView.js
- pages/course/index.js
- styles/globals.css
Jira: [HYP-151](https://happyelders.atlassian.net/browse/HYP-151)
style: change height, grid, course name padding
> [HYP-151]fix card course

- components/FooterSocial.js
- package-lock.json
- package.json
Jira: [HYP-152](https://happyelders.atlassian.net/browse/HYP-152)
+ when in mobile view change to text "Click to send email"
> [HYP-152]create email form to send when click email at footer
